[package]
name = "intune_core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
keyring = { version = "3", default-features = false, features = ["apple-native", "windows-native", "linux-native"] }
